# This is a basic workflow to help you get started with Actions

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - frontend
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install
          npm run build  # Adjust based on your framework (vite, next, etc.)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist # or ./build depending on your tool

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy to GitHub Pages
        uses: actions/checkout@v4
